application: udacitygeorge1
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /js
  static_dir: static
  
- url: /css
  static_dir: static

- url: /.*
  script: blog.app
  
  
libraries:
- name: jinja2
  version: latest